
version: 2

models:
  - name: sales_top_5_items
    description: "Overall Top 5 Total Sales on all items."
    columns:
      - name: StockCode
        description: "The primary key for this table"
        tests:
          - unique
          - not_null